### ISSUE TITLE
Topics Page - Create Toolbar / Table in Card View

### ISSUE THREAD

**Issue by christiemolloy** [uxd-mk-prototype/uxd-mk-data-plane-ui#3]
- Create the card view, toolbar and table in the topic homepage.
- Create topic and example topic are already in this page because they open up the wizards.

https://marvelapp.com/prototype/26598gag/screen/73803101

**Comment by christiemolloy** [comment]
Do you want to add Search functionality ?
Should each of the dropdown kebabs be able to open? should it have dummy links ?
Should you be able to paginate through? or should there just be the data that is in that example so pagination is disabled?

**Comment by jgiardino** [comment]
> Do you want to add Search functionality ?

For the prototype, I'd say we include the input, but not implement the functionality. For a previous react-based prototype, I included a popover for buttons to say that the functionality for that button isn't implemented in this prototype, which works fine for a user test. I have never tried putting a popover on an input, though. Maybe a tooltip when the input has focus would work? If not, we can just let the moderator know that this doesn't work if the participant tries to interact with it.

> Should each of the dropdown kebabs be able to open? should it have dummy links ?

Yes, and yes. This is really helpful to have for user testing. 
@lboehling - Do you have details on what actions are meant to display in a kebab for a topic?

> Should you be able to paginate through? or should there just be the data that is in that example so pagination is disabled?

I would not implement pagination for this, so having just fewer than one page of topics sounds good.

**Comment by jgiardino** [comment]
FYI, I included a separate issue to capture how we want to handle communicating controls that aren't fully functional: #12

**Comment by lboehling** [comment]
@christiemolloy @jgiardino I think the only action in the kebab menu currently is "delete topic." This actually differs from the carbon UI for Strimzi (they only have delete topic under the properties tab in the topic details pages). I added in the kebab after a discussion with the MK team where it was mentioned that delete should be surfaced on the topic list page too.

**Comment by christiemolloy** [comment]
@jgiardino @lboehling do you want me to add in functionality to delete it (again once the user refreshes the state will update back to the original)

**Comment by christiemolloy** [comment]
@lboehling for the Topics page. How do you get from the name of a topic to this screen? https://marvelapp.com/prototype/26598gag/screen/73803103 are all the topics on the topic page, links?

**Comment by jgiardino** [comment]
> @jgiardino @lboehling do you want me to add in functionality to delete it (again once the user refreshes the state will update back to the original)

I created #16 to capture this, and included a `stretch item` label on it. I imagine there will be other things like this that would be nice to have, or not known yet if they're required for user testing, and for items like this, let's just track them separately and come back to them if we have time or they're identified as being critical for user testing.

**Comment by lboehling** [comment]
> @lboehling for the Topics page. How do you get from the name of a topic to this screen? https://marvelapp.com/prototype/26598gag/screen/73803103 are all the topics on the topic page, links?

The rows should be clickable and link to the topic details pages. If clickable rows don't work, I'm fine w implementing just the topic names as links.  @christiemolloy

**Comment by christiemolloy** [comment]
@lboehling should this be a dropdown with text next to it ? or should we just make this a string "Topics per page: 10", and then remove the dropdown functionality - to make it easier. As per Jenn's comment above we arent implementing pagination so will have less than 10 items on the page.
<img width="180" alt="Screen Shot 2020-10-28 at 2 51 29 PM" src="https://user-images.githubusercontent.com/20118816/97482921-2b8fd000-192d-11eb-9542-2c2e4552412f.png">

**Comment by christiemolloy** [comment]
> > @lboehling for the Topics page. How do you get from the name of a topic to this screen? https://marvelapp.com/prototype/26598gag/screen/73803103 are all the topics on the topic page, links?
> 
> The rows should be clickable and link to the topic details pages. If clickable rows don't work, I'm fine w implementing just the topic names as links. @christiemolloy

@lboehling Was there a particular table example in here you are referring to https://www.patternfly.org/v4/components/table, i think only Data list has selectable rows. Ill make it a link for now ?

**Comment by lboehling** [comment]
I didn't realize clickable rows weren't an option for data tables! Let's just do the links then :) 

I'm fine with just leaving the topics per page as a string and remove the dropdown functionality. 

@christiemolloy
